version: '3.8'

services:
  app:
    build: .
    ports:
      - "5655:5655"
    environment:
      - DB_HOST=172.19.0.3
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=docker

    restart: unless-stopped
